name: Deploy Fullstack to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------------
      # CLIENT BUILD
      # ---------------------
      - name: Install client deps
        run: npm install
        working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client

      # ---------------------
      # SERVER BUILD (TypeScript)
      # ---------------------
      - name: Install server deps
        run: npm install
        working-directory: server

      - name: Build server
        run: npm run build
        working-directory: server

      # ---------------------
      # DEPLOY TO EC2
      # ---------------------
      - name: Upload CLIENT to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "client/dist/*"
          target: "/var/www/html/client"

      - name: Upload SERVER to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
